# Generated by Django 5.2.4 on 2025-07-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactfinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email_patterns',
            field=models.JSONField(default=list, help_text="Ranked email patterns for this domain with confidence scores. Structure: [{  'pattern': 'first.last',   'confidence': 0.95,   'source': 'verified_emails'  # verified_emails|api_lookup|scraped}] "),
        ),
    ]
