from .advanced_prompts import (
    COMPANY_EMAIL_DOMAIN_PROMPT_V1,
    COMPANY_EMAIL_DOMAIN_PROMPT_V2,
    COMPANY_EMAIL_DOMAIN_PROMPT_V3,
    EMPLOYEE_EMAIL_PROMPT_V1,
    EMPLOYEE_EMAIL_PROMPT_V2,
    EMPLOYEE_EMAIL_PROMPT_V3,
)

__all__ = [
    "COMPANY_EMAIL_DOMAIN_PROMPT_V1",
    "COMPANY_EMAIL_DOMAIN_PROMPT_V2",
    "COMPANY_EMAIL_DOMAIN_PROMPT_V3",
    "EMPLOYEE_EMAIL_PROMPT_V1",
    "EMPLOYEE_EMAIL_PROMPT_V2",
    "EMPLOYEE_EMAIL_PROMPT_V3",
]
